
CREATE SCHEMA memory.schema_01;
CREATE TABLE memory.schema_01.table_01 as select 1 x;
CREATE TABLE memory.schema_01.table_02 as select 1 x;
CREATE TABLE memory.schema_01.table_03 as select 1 x;
CREATE TABLE memory.schema_01.table_04 as select 1 x;
CREATE TABLE memory.schema_01.table_05 as select 1 x;
CREATE TABLE memory.schema_01.table_06 as select 1 x;
CREATE TABLE memory.schema_01.table_07 as select 1 x;
CREATE TABLE memory.schema_01.table_08 as select 1 x;
CREATE TABLE memory.schema_01.table_09 as select 1 x;
CREATE TABLE memory.schema_01.table_10 as select 1 x;
CREATE SCHEMA memory.schema_02;
CREATE TABLE memory.schema_02.table_01 as select 1 x;
CREATE TABLE memory.schema_02.table_02 as select 1 x;
CREATE TABLE memory.schema_02.table_03 as select 1 x;
CREATE TABLE memory.schema_02.table_04 as select 1 x;
CREATE TABLE memory.schema_02.table_05 as select 1 x;
CREATE TABLE memory.schema_02.table_06 as select 1 x;
CREATE TABLE memory.schema_02.table_07 as select 1 x;
CREATE TABLE memory.schema_02.table_08 as select 1 x;
CREATE TABLE memory.schema_02.table_09 as select 1 x;
CREATE TABLE memory.schema_02.table_10 as select 1 x;
CREATE SCHEMA memory.schema_03;
CREATE TABLE memory.schema_03.table_01 as select 1 x;
CREATE TABLE memory.schema_03.table_02 as select 1 x;
CREATE TABLE memory.schema_03.table_03 as select 1 x;
CREATE TABLE memory.schema_03.table_04 as select 1 x;
CREATE TABLE memory.schema_03.table_05 as select 1 x;
CREATE TABLE memory.schema_03.table_06 as select 1 x;
CREATE TABLE memory.schema_03.table_07 as select 1 x;
CREATE TABLE memory.schema_03.table_08 as select 1 x;
CREATE TABLE memory.schema_03.table_09 as select 1 x;
CREATE TABLE memory.schema_03.table_10 as select 1 x;
CREATE SCHEMA memory.schema_04;
CREATE TABLE memory.schema_04.table_01 as select 1 x;
CREATE TABLE memory.schema_04.table_02 as select 1 x;
CREATE TABLE memory.schema_04.table_03 as select 1 x;
CREATE TABLE memory.schema_04.table_04 as select 1 x;
CREATE TABLE memory.schema_04.table_05 as select 1 x;
CREATE TABLE memory.schema_04.table_06 as select 1 x;
CREATE TABLE memory.schema_04.table_07 as select 1 x;
CREATE TABLE memory.schema_04.table_08 as select 1 x;
CREATE TABLE memory.schema_04.table_09 as select 1 x;
CREATE TABLE memory.schema_04.table_10 as select 1 x;
CREATE SCHEMA memory.schema_05;
CREATE TABLE memory.schema_05.table_01 as select 1 x;
CREATE TABLE memory.schema_05.table_02 as select 1 x;
CREATE TABLE memory.schema_05.table_03 as select 1 x;
CREATE TABLE memory.schema_05.table_04 as select 1 x;
CREATE TABLE memory.schema_05.table_05 as select 1 x;
CREATE TABLE memory.schema_05.table_06 as select 1 x;
CREATE TABLE memory.schema_05.table_07 as select 1 x;
CREATE TABLE memory.schema_05.table_08 as select 1 x;
CREATE TABLE memory.schema_05.table_09 as select 1 x;
CREATE TABLE memory.schema_05.table_10 as select 1 x;
